#!/bin/python3
from flask import Flask
from flask import request
import os
from flask import Flask, redirect, render_template, request, url_for, send_file
from flask import Flask, request, send_from_directory
from datetime import datetime

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = "/home/adam/android_stuff/rtc/"

@app.route('/finish', methods=['POST'])
def finish():
    print('finish method on python server',request.files,request.values["start"])
    if request.method == 'POST':
        if "video-blob" in request.files:
          video_file = request.files['video-blob']
          #video_file.save(os.path.join(app.config['UPLOAD_FOLDER'],         datetime.now().strftime('%Y-%m-%d-%H-%M-%S')+ request.values['video-filename'] ))
          video_file.save("/tmp/upload_temp")
          os.system("ffmpeg -i /tmp/upload_temp -ss "+request.values["start"]+" -c copy "+ os.path.join(app.config['UPLOAD_FOLDER'],         datetime.now().strftime('%Y-%m-%d-%H-%M-%S')+ request.values['video-filename'] ) )
          return 'Got video file!'

#@app.route('/<path:path>')
#def static_file(path):
#    return app.send_static_file(path)
 
@app.route('/', methods=['GET'])
def redirect_to_index():
    return send_file('simple-demos/auto-stop-on-silence.html')           
 
@app.route('/<path:path>')
def static_file(path):
    return send_from_directory(".",path)
    
           
app.run(host='0.0.0.0', port=5432)

